// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx42Wr2AKk_ysL3ODkrqYMiByedz9yXPE',
    appId: '1:957901643662:web:4955d1479aa03894b54edf',
    messagingSenderId: '957901643662',
    projectId: 'coffeecom-57d1d',
    authDomain: 'coffeecom-57d1d.firebaseapp.com',
    storageBucket: 'coffeecom-57d1d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVLG-hnHohaDQAZWxnm2gI208nH_RO-8Q',
    appId: '1:957901643662:android:87ae650fb01bb2d5b54edf',
    messagingSenderId: '957901643662',
    projectId: 'coffeecom-57d1d',
    storageBucket: 'coffeecom-57d1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6W3ADuF1eERcADOEMorsDMfef3Y3xOiE',
    appId: '1:957901643662:ios:038aa833f5541948b54edf',
    messagingSenderId: '957901643662',
    projectId: 'coffeecom-57d1d',
    storageBucket: 'coffeecom-57d1d.appspot.com',
    iosBundleId: 'com.example.coffeEcom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6W3ADuF1eERcADOEMorsDMfef3Y3xOiE',
    appId: '1:957901643662:ios:114316b45a2fb002b54edf',
    messagingSenderId: '957901643662',
    projectId: 'coffeecom-57d1d',
    storageBucket: 'coffeecom-57d1d.appspot.com',
    iosBundleId: 'com.example.coffeEcom.RunnerTests',
  );
}
